export const START_LOADING = 'START_LOADING',
  CLEAR_ERRORS = 'CLEAR_ERRORS',
  CHARACTERS_LOADED = 'CHARACTERS_LOADED',
  CHARACTERS_ERROR = 'CHARACTERS_ERROR',
  FILTER_GENDER = 'FITER_GENDER',
  FILTER_CULTURE = 'FILTER_CULTURE',
  HOUSES_LOADED = 'HOUSES_LOADED',
  HOUSES_ERROR = 'HOUSES_ERROR';
